### ISSUE TITLE
Incorrect "What next?" suggestion?

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/gravity-simulator#3]
Under that "What next?" at the bottom of the worksheet, it suggests "If you have a Sense HAT, could you use it to trigger the timer instead of using the keyboard?" but there's no mention of a timer anywhere else in the worksheet.
Looks like it might be a copy'n'paste error from the bottom of https://www.raspberrypi.org/learning/astronaut-reaction-times/worksheet/ ?

**Comment by LornaLynch** [comment]
It looks as if @lauraclay has fixed this :)
